MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/p_vinsentds/maskrcnn-benchmark/model_final.pth"
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    SHARE_BOX_FEATURE_EXTRACTOR: True
  MASK_ON: True
DATASETS:
  TRAIN: ("micr_2017_train", "micr_2017_valminusminival")
  TEST: ("micr_2017_val",)