MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/madhevan/maskrcnn-benchmark/last_checkpoint"
  RPN:
    PRE_NMS_TOP_N_TEST: 60
    POST_NMS_TOP_N_TEST: 10
DATASETS:
  TRAIN: ("micr_2017_train", "micr_2017_valminusminival")
  TEST: ("micr_2017_val",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120, 160)
  MAX_ITER: 50
  IMS_PER_BATCH: 4
