MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/p_vinsentds/maskrcnn-benchmark/model_0070000.pth"
  RPN:
    PRE_NMS_TOP_N_TEST: 600
    POST_NMS_TOP_N_TEST: 100
DATASETS:
  TRAIN: ("micr_2017_train", "micr_2017_valminusminival")
  TEST: ("micr_2017_val",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120, 160)
  MAX_ITER: 50000
  IMS_PER_BATCH: 4
