MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 600
    POST_NMS_TOP_N_TEST: 100
DATASETS:
  TRAIN: ("micr_2017_train", "micr_2017_valminusminival")
  TEST: ("micr_2017_val",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (1200, 1600)
  MAX_ITER: 180000
  IMS_PER_BATCH: 8
